logging:
  level: "${LOG_LEVEL_MAIN}"
  loggers:
    codingchica: "INFO"
flashCardGroupMap:
  Addition:
  - name: "Adding 0"
    maximumPrompts: 20
    minimumPrompts: 20
    prompts:
      "0+0": 0
      "0+1": 1
      "0+10": 10
      "0+11": 11
      "0+12": 12
      "0+2": 2
      "0+3": 3
      "0+4": 4
      "0+5": 5
      "0+6": 6
      "0+7": 7
      "0+8": 8
      "0+9": 9
      "1+0": 1
      "10+0": 10
      "11+0": 11
      "12+0": 12
      "2+0": 2
      "3+0": 3
      "4+0": 4
      "5+0": 5
      "6+0": 6
      "7+0": 7
      "8+0": 8
      "9+0": 9
  - name: "Adding 1"
    maximumPrompts: 20
    minimumPrompts: 20
    prompts:
      "0+1": 1
      "1+1": 2
      "2+1": 3
      "3+1": 4
      "4+1": 5
      "5+1": 6
      "6+1": 7
      "7+1": 8
      "8+1": 9
      "9+1": 10
      "1+0": 1
      "1+2": 3
      "1+3": 4
      "1+4": 5
      "1+5": 6
      "1+6": 7
      "1+7": 8
      "1+8": 9
      "1+9": 10
      "1+10": 11
      "1+11": 12
      "1+12": 13
      "10+1": 11
      "11+1": 12
      "12+1": 13
  - name: "Adding 2"
    maximumPrompts: 20
    minimumPrompts: 20
    prompts:
      "2+0": 2
      "0+2": 2
      "2+1": 3
      "1+2": 3
      "2+2": 4
      "2+3": 5
      "3+2": 5
      "2+4": 6
      "4+2": 6
      "2+5": 7
      "5+2": 7
      "2+6": 8
      "6+2": 8
      "2+7": 9
      "7+2": 9
      "2+8": 10
      "8+2": 10
      "2+9": 11
      "9+2": 11
      "2+10": 12
      "10+2": 12
      "2+11": 13
      "11+2": 13
      "2+12": 14
      "12+2": 14
  - name: "Adding 3"
    maximumPrompts: 20
    minimumPrompts: 20
    prompts:
      "0+3": 3
      "1+3": 4
      "10+3": 13
      "11+3": 14
      "12+3": 15
      "2+3": 5
      "3+0": 3
      "3+1": 4
      "3+10": 13
      "3+11": 14
      "3+12": 15
      "3+2": 5
      "3+3": 6
      "3+4": 7
      "3+5": 8
      "3+6": 9
      "3+7": 10
      "3+8": 11
      "3+9": 12
      "4+3": 7
      "5+3": 8
      "6+3": 9
      "7+3": 10
      "8+3": 11
      "9+3": 12
  - name: "Adding 4"
    maximumPrompts: 20
    minimumPrompts: 20
    prompts:
      "0+4": 4
      "1+4": 5
      "10+4": 14
      "11+4": 15
      "12+4": 16
      "2+4": 6
      "3+4": 7
      "4+0": 4
      "4+1": 5
      "4+10": 14
      "4+11": 15
      "4+12": 16
      "4+2": 6
      "4+3": 7
      "4+4": 8
      "4+5": 9
      "4+6": 10
      "4+7": 11
      "4+8": 12
      "4+9": 13
      "5+4": 9
      "6+4": 10
      "7+4": 11
      "8+4": 12
      "9+4": 13
  - name: "Adding 5"
    maximumPrompts: 20
    minimumPrompts: 20
    prompts:
      "0+5": 5
      "1+5": 6
      "10+5": 15
      "11+5": 16
      "12+5": 17
      "2+5": 7
      "3+5": 8
      "4+5": 9
      "5+0": 5
      "5+1": 6
      "5+10": 15
      "5+11": 16
      "5+12": 17
      "5+2": 7
      "5+3": 8
      "5+4": 9
      "5+5": 10
      "5+6": 11
      "5+7": 12
      "5+8": 13
      "5+9": 14
      "6+5": 11
      "7+5": 12
      "8+5": 13
      "9+5": 14
  - name: "Adding 6"
    maximumPrompts: 20
    minimumPrompts: 20
    prompts:
      "0+6": 6
      "1+6": 7
      "10+6": 16
      "11+6": 17
      "12+6": 18
      "2+6": 8
      "3+6": 9
      "4+6": 10
      "5+6": 11
      "6+0": 6
      "6+1": 7
      "6+10": 16
      "6+11": 17
      "6+12": 18
      "6+2": 8
      "6+3": 9
      "6+4": 10
      "6+5": 11
      "6+6": 12
      "6+7": 13
      "6+8": 14
      "6+9": 15
      "7+6": 13
      "8+6": 14
      "9+6": 15
  - name: "Adding 7"
    maximumPrompts: 20
    minimumPrompts: 20
    prompts:
      "0+7": 7
      "1+7": 8
      "10+7": 17
      "11+7": 18
      "12+7": 19
      "2+7": 9
      "3+7": 10
      "4+7": 11
      "5+7": 12
      "6+7": 13
      "7+0": 7
      "7+1": 8
      "7+10": 17
      "7+11": 18
      "7+12": 19
      "7+2": 9
      "7+3": 10
      "7+4": 11
      "7+5": 12
      "7+6": 13
      "7+7": 14
      "7+8": 15
      "7+9": 16
      "8+7": 15
      "9+7": 16
  - name: "Adding 8"
    maximumPrompts: 20
    minimumPrompts: 20
    prompts:
      "0+8": 8
      "1+8": 9
      "10+8": 18
      "11+8": 19
      "12+8": 20
      "2+8": 10
      "3+8": 11
      "4+8": 12
      "5+8": 13
      "6+8": 14
      "7+8": 15
      "8+0": 8
      "8+1": 9
      "8+10": 18
      "8+11": 19
      "8+12": 20
      "8+2": 10
      "8+3": 11
      "8+4": 12
      "8+5": 13
      "8+6": 14
      "8+7": 15
      "8+8": 16
      "8+9": 17
      "9+8": 17
  - name: "Adding 9"
    maximumPrompts: 20
    minimumPrompts: 20
    prompts:
      "0+9": 9
      "1+9": 10
      "10+9": 19
      "11+9": 20
      "12+9": 21
      "2+9": 11
      "3+9": 12
      "4+9": 13
      "5+9": 14
      "6+9": 15
      "7+9": 16
      "8+9": 17
      "9+0": 9
      "9+1": 10
      "9+10": 19
      "9+11": 20
      "9+12": 21
      "9+2": 11
      "9+3": 12
      "9+4": 13
      "9+5": 14
      "9+6": 15
      "9+7": 16
      "9+8": 17
      "9+9": 18
  - name: "Adding 10"
    maximumPrompts: 20
    minimumPrompts: 20
    prompts:
      "0+10": 10
      "1+10": 11
      "10+0": 10
      "10+1": 11
      "10+10": 20
      "10+11": 21
      "10+12": 22
      "10+2": 12
      "10+3": 13
      "10+4": 14
      "10+5": 15
      "10+6": 16
      "10+7": 17
      "10+8": 18
      "10+9": 19
      "11+10": 21
      "12+10": 22
      "2+10": 12
      "3+10": 13
      "4+10": 14
      "5+10": 15
      "6+10": 16
      "7+10": 17
      "8+10": 18
      "9+10": 19
  - name: "Adding 11"
    maximumPrompts: 20
    minimumPrompts: 20
    prompts:
      "0+11": 11
      "1+11": 12
      "10+11": 21
      "11+0": 11
      "11+1": 12
      "11+10": 21
      "11+11": 22
      "11+12": 23
      "11+2": 13
      "11+3": 14
      "11+4": 15
      "11+5": 16
      "11+6": 17
      "11+7": 18
      "11+8": 19
      "11+9": 20
      "12+11": 23
      "2+11": 13
      "3+11": 14
      "4+11": 15
      "5+11": 16
      "6+11": 17
      "7+11": 18
      "8+11": 19
      "9+11": 20
  - name: "Adding 12"
    maximumPrompts: 20
    minimumPrompts: 20
    prompts:
      "0+12": 12
      "1+12": 13
      "10+12": 22
      "11+12": 23
      "12+0": 12
      "12+1": 13
      "12+10": 22
      "12+11": 23
      "12+12": 24
      "12+2": 14
      "12+3": 15
      "12+4": 16
      "12+5": 17
      "12+6": 18
      "12+7": 19
      "12+8": 20
      "12+9": 21
      "2+12": 14
      "3+12": 15
      "4+12": 16
      "5+12": 17
      "6+12": 18
      "7+12": 19
      "8+12": 20
      "9+12": 21
  Subtraction:
  - name: "Subtracting 0"
    maximumPrompts: 20
    minimumPrompts: 20
    prompts:
      "0-0": 0
      "1-0": 1
      "10-0": 10
      "11-0": 11
      "12-0": 12
      "2-0": 2
      "3-0": 3
      "4-0": 4
      "5-0": 5
      "6-0": 6
      "7-0": 7
      "8-0": 8
      "9-0": 9
  - name: "Subtracting 1"
    maximumPrompts: 20
    minimumPrompts: 20
    prompts:
      "1-1": 0
      "10-1": 9
      "11-1": 10
      "12-1": 11
      "13-1": 12
      "2-1": 1
      "3-1": 2
      "4-1": 3
      "5-1": 4
      "6-1": 5
      "7-1": 6
      "8-1": 7
      "9-1": 8
  - name: "Subtracting 2"
    maximumPrompts: 20
    minimumPrompts: 20
    prompts:
      "10-2": 8
      "11-2": 9
      "12-2": 10
      "13-2": 11
      "14-2": 12
      "2-2": 0
      "3-2": 1
      "4-2": 2
      "5-2": 3
      "6-2": 4
      "7-2": 5
      "8-2": 6
      "9-2": 7
  - name: "Subtracting 3"
    maximumPrompts: 20
    minimumPrompts: 20
    prompts:
      "10-3": 7
      "11-3": 8
      "12-3": 9
      "13-3": 10
      "14-3": 11
      "15-3": 12
      "3-3": 0
      "4-3": 1
      "5-3": 2
      "6-3": 3
      "7-3": 4
      "8-3": 5
      "9-3": 6
  - name: "Subtracting 4"
    maximumPrompts: 20
    minimumPrompts: 20
    prompts:
      "10-4": 6
      "11-4": 7
      "12-4": 8
      "13-4": 9
      "14-4": 10
      "15-4": 11
      "16-4": 12
      "4-4": 0
      "5-4": 1
      "6-4": 2
      "7-4": 3
      "8-4": 4
      "9-4": 5
  - name: "Subtracting 5"
    maximumPrompts: 20
    minimumPrompts: 20
    prompts:
      "10-5": 5
      "11-5": 6
      "12-5": 7
      "13-5": 8
      "14-5": 9
      "15-5": 10
      "16-5": 11
      "17-5": 12
      "5-5": 0
      "6-5": 1
      "7-5": 2
      "8-5": 3
      "9-5": 4
  - name: "Subtracting 6"
    maximumPrompts: 20
    minimumPrompts: 20
    prompts:
      "10-6": 4
      "11-6": 5
      "12-6": 6
      "13-6": 7
      "14-6": 8
      "15-6": 9
      "16-6": 10
      "17-6": 11
      "18-6": 12
      "6-6": 0
      "7-6": 1
      "8-6": 2
      "9-6": 3
  - name: "Subtracting 7"
    maximumPrompts: 20
    minimumPrompts: 20
    prompts:
      "10-7": 3
      "11-7": 4
      "12-7": 5
      "13-7": 6
      "14-7": 7
      "15-7": 8
      "16-7": 9
      "17-7": 10
      "18-7": 11
      "19-7": 12
      "7-7": 0
      "8-7": 1
      "9-7": 2
  - name: "Subtracting 8"
    maximumPrompts: 20
    minimumPrompts: 20
    prompts:
      "10-8": 2
      "11-8": 3
      "12-8": 4
      "13-8": 5
      "14-8": 6
      "15-8": 7
      "16-8": 8
      "17-8": 9
      "18-8": 10
      "19-8": 11
      "20-8": 12
      "8-8": 0
      "9-8": 1
  - name: "Subtracting 9"
    maximumPrompts: 20
    minimumPrompts: 20
    prompts:
      "10-9": 1
      "11-9": 2
      "12-9": 3
      "13-9": 4
      "14-9": 5
      "15-9": 6
      "16-9": 7
      "17-9": 8
      "18-9": 9
      "19-9": 10
      "20-9": 11
      "21-9": 12
      "9-9": 0
  - name: "Subtracting 10"
    maximumPrompts: 20
    minimumPrompts: 20
    prompts:
      "10-10": 0
      "11-10": 1
      "12-10": 2
      "13-10": 3
      "14-10": 4
      "15-10": 5
      "16-10": 6
      "17-10": 7
      "18-10": 8
      "19-10": 9
      "20-10": 10
      "21-10": 11
      "22-10": 12
  - name: "Subtracting 11"
    maximumPrompts: 20
    minimumPrompts: 20
    prompts:
      "11-11": 0
      "12-11": 1
      "13-11": 2
      "14-11": 3
      "15-11": 4
      "16-11": 5
      "17-11": 6
      "18-11": 7
      "19-11": 8
      "20-11": 9
      "21-11": 10
      "22-11": 11
      "23-11": 12
  - name: "Subtracting 12"
    maximumPrompts: 20
    minimumPrompts: 20
    prompts:
      "12-12": 0
      "13-12": 1
      "14-12": 2
      "15-12": 3
      "16-12": 4
      "17-12": 5
      "18-12": 6
      "19-12": 7
      "20-12": 8
      "21-12": 9
      "22-12": 10
      "23-12": 11
      "24-12": 12
  Multiplication:
  - name: "Multiplying By 0"
    maximumPrompts: 20
    minimumPrompts: 20
    prompts:
      "0x0": 0
      "10x0": 0
      "11x0": 0
      "12x0": 0
      "1x0": 0
      "2x0": 0
      "3x0": 0
      "4x0": 0
      "5x0": 0
      "6x0": 0
      "7x0": 0
      "8x0": 0
      "9x0": 0
  - name: "Multiplying By 1"
    maximumPrompts: 20
    minimumPrompts: 20
    prompts:
      "0x1": 0
      "10x1": 10
      "11x1": 11
      "12x1": 12
      "1x1": 1
      "2x1": 2
      "3x1": 3
      "4x1": 4
      "5x1": 5
      "6x1": 6
      "7x1": 7
      "8x1": 8
      "9x1": 9
  - name: "Multiplying By 2"
    maximumPrompts: 20
    minimumPrompts: 20
    prompts:
      "0x2": 0
      "10x2": 20
      "11x2": 22
      "12x2": 24
      "1x2": 2
      "2x2": 4
      "3x2": 6
      "4x2": 8
      "5x2": 10
      "6x2": 12
      "7x2": 14
      "8x2": 16
      "9x2": 18
  - name: "Multiplying By 3"
    maximumPrompts: 20
    minimumPrompts: 20
    prompts:
      "0x3": 0
      "10x3": 30
      "11x3": 33
      "12x3": 36
      "1x3": 3
      "2x3": 6
      "3x3": 9
      "4x3": 12
      "5x3": 15
      "6x3": 18
      "7x3": 21
      "8x3": 24
      "9x3": 27
  - name: "Multiplying By 4"
    maximumPrompts: 20
    minimumPrompts: 20
    prompts:
      "0x4": 0
      "10x4": 40
      "11x4": 44
      "12x4": 48
      "1x4": 4
      "2x4": 8
      "3x4": 12
      "4x4": 16
      "5x4": 20
      "6x4": 24
      "7x4": 28
      "8x4": 32
      "9x4": 36
  - name: "Multiplying By 5"
    maximumPrompts: 20
    minimumPrompts: 20
    prompts:
      "0x5": 0
      "10x5": 50
      "11x5": 55
      "12x5": 60
      "1x5": 5
      "2x5": 10
      "3x5": 15
      "4x5": 20
      "5x5": 25
      "6x5": 30
      "7x5": 35
      "8x5": 40
      "9x5": 45
  - name: "Multiplying By 6"
    maximumPrompts: 20
    minimumPrompts: 20
    prompts:
      "0x6": 0
      "10x6": 60
      "11x6": 66
      "12x6": 72
      "1x6": 6
      "2x6": 12
      "3x6": 18
      "4x6": 24
      "5x6": 30
      "6x6": 36
      "7x6": 42
      "8x6": 48
      "9x6": 54
  - name: "Multiplying By 7"
    maximumPrompts: 20
    minimumPrompts: 20
    prompts:
      "0x7": 0
      "10x7": 70
      "11x7": 77
      "12x7": 84
      "1x7": 7
      "2x7": 14
      "3x7": 21
      "4x7": 28
      "5x7": 35
      "6x7": 42
      "7x7": 49
      "8x7": 56
      "9x7": 63
  - name: "Multiplying By 8"
    maximumPrompts: 20
    minimumPrompts: 20
    prompts:
      "0x8": 0
      "10x8": 80
      "11x8": 88
      "12x8": 96
      "1x8": 8
      "2x8": 16
      "3x8": 24
      "4x8": 32
      "5x8": 40
      "6x8": 48
      "7x8": 56
      "8x8": 64
      "9x8": 72
  - name: "Multiplying By 9"
    maximumPrompts: 20
    minimumPrompts: 20
    prompts:
      "0x9": 0
      "10x9": 90
      "11x9": 99
      "12x9": 108
      "1x9": 9
      "2x9": 18
      "3x9": 27
      "4x9": 36
      "5x9": 45
      "6x9": 54
      "7x9": 63
      "8x9": 72
      "9x9": 81
  - name: "Multiplying By 10"
    maximumPrompts: 20
    minimumPrompts: 20
    prompts:
      "0x10": 0
      "10x10": 100
      "11x10": 110
      "12x10": 120
      "1x10": 10
      "2x10": 20
      "3x10": 30
      "4x10": 40
      "5x10": 50
      "6x10": 60
      "7x10": 70
      "8x10": 80
      "9x10": 90
  - name: "Multiplying By 11"
    maximumPrompts: 20
    minimumPrompts: 20
    prompts:
      "0x11": 0
      "10x11": 110
      "11x11": 121
      "12x11": 132
      "1x11": 11
      "2x11": 22
      "3x11": 33
      "4x11": 44
      "5x11": 55
      "6x11": 66
      "7x11": 77
      "8x11": 88
      "9x11": 99
  - name: "Multiplying By 12"
    maximumPrompts: 20
    minimumPrompts: 20
    prompts:
      "0x12": 0
      "10x12": 120
      "11x12": 132
      "12x12": 144
      "1x12": 12
      "2x12": 24
      "3x12": 36
      "4x12": 48
      "5x12": 60
      "6x12": 72
      "7x12": 84
      "8x12": 96
      "9x12": 108
  Division:
  - name: "Dividing By 1"
    maximumPrompts: 20
    minimumPrompts: 20
    prompts:
      "0/1": 0
      "1/1": 1
      "10/1": 10
      "11/1": 11
      "12/1": 12
      "2/1": 2
      "3/1": 3
      "4/1": 4
      "5/1": 5
      "6/1": 6
      "7/1": 7
      "8/1": 8
      "9/1": 9
  - name: "Dividing By 2"
    maximumPrompts: 20
    minimumPrompts: 20
    prompts:
      "0/2": 0
      "10/2": 5
      "12/2": 6
      "14/2": 7
      "16/2": 8
      "18/2": 9
      "2/2": 1
      "20/2": 10
      "22/2": 11
      "24/2": 12
      "4/2": 2
      "6/2": 3
      "8/2": 4
  - name: "Dividing By 3"
    maximumPrompts: 20
    minimumPrompts: 20
    prompts:
      "0/3": 0
      "12/3": 4
      "15/3": 5
      "18/3": 6
      "21/3": 7
      "24/3": 8
      "27/3": 9
      "3/3": 1
      "30/3": 10
      "33/3": 11
      "36/3": 12
      "6/3": 2
      "9/3": 3
  - name: "Dividing By 4"
    maximumPrompts: 20
    minimumPrompts: 20
    prompts:
      "0/4": 0
      "12/4": 3
      "16/4": 4
      "20/4": 5
      "24/4": 6
      "28/4": 7
      "32/4": 8
      "36/4": 9
      "4/4": 1
      "40/4": 10
      "44/4": 11
      "48/4": 12
      "8/4": 2
  - name: "Dividing By 5"
    maximumPrompts: 20
    minimumPrompts: 20
    prompts:
      "0/5": 0
      "10/5": 2
      "15/5": 3
      "20/5": 4
      "25/5": 5
      "30/5": 6
      "35/5": 7
      "40/5": 8
      "45/5": 9
      "5/5": 1
      "50/5": 10
      "55/5": 11
      "60/5": 12
  - name: "Dividing By 6"
    maximumPrompts: 20
    minimumPrompts: 20
    prompts:
      "0/6": 0
      "12/6": 2
      "18/6": 3
      "24/6": 4
      "30/6": 5
      "36/6": 6
      "42/6": 7
      "48/6": 8
      "54/6": 9
      "6/6": 1
      "60/6": 10
      "66/6": 11
      "72/6": 12
  - name: "Dividing By 7"
    maximumPrompts: 20
    minimumPrompts: 20
    prompts:
      "0/7": 0
      "14/7": 2
      "21/7": 3
      "28/7": 4
      "35/7": 5
      "42/7": 6
      "49/7": 7
      "56/7": 8
      "63/7": 9
      "7/7": 1
      "70/7": 10
      "77/7": 11
      "84/7": 12
  - name: "Dividing By 8"
    maximumPrompts: 20
    minimumPrompts: 20
    prompts:
      "0/8": 0
      "16/8": 2
      "24/8": 3
      "32/8": 4
      "40/8": 5
      "48/8": 6
      "56/8": 7
      "64/8": 8
      "72/8": 9
      "8/8": 1
      "80/8": 10
      "88/8": 11
      "96/8": 12
  - name: "Dividing By 9"
    maximumPrompts: 20
    minimumPrompts: 20
    prompts:
      "0/9": 0
      "108/9": 12
      "18/9": 2
      "27/9": 3
      "36/9": 4
      "45/9": 5
      "54/9": 6
      "63/9": 7
      "72/9": 8
      "81/9": 9
      "9/9": 1
      "90/9": 10
      "99/9": 11
  - name: "Dividing By 10"
    maximumPrompts: 20
    minimumPrompts: 20
    prompts:
      "0/10": 0
      "10/10": 1
      "100/10": 10
      "110/10": 11
      "120/10": 12
      "20/10": 2
      "30/10": 3
      "40/10": 4
      "50/10": 5
      "60/10": 6
      "70/10": 7
      "80/10": 8
      "90/10": 9
  - name: "Dividing By 11"
    maximumPrompts: 20
    minimumPrompts: 20
    prompts:
      "0/11": 0
      "11/11": 1
      "110/11": 10
      "121/11": 11
      "132/11": 12
      "22/11": 2
      "33/11": 3
      "44/11": 4
      "55/11": 5
      "66/11": 6
      "77/11": 7
      "88/11": 8
      "99/11": 9
  - name: "Dividing By 12"
    maximumPrompts: 20
    minimumPrompts: 20
    prompts:
      "0/12": 0
      "108/12": 9
      "12/12": 1
      "120/12": 10
      "132/12": 11
      "144/12": 12
      "24/12": 2
      "36/12": 3
      "48/12": 4
      "60/12": 5
      "72/12": 6
      "84/12": 7
      "96/12": 8
